### PR TITLE
Translate timestamper plugin into chinese

### PR DESCRIPTION
**Pull request by yuezhuangshi**
### Submitter checklist

- [x] [Know translation specification](https://github.com/jenkins-zh/translation-spec/blob/master/specification.md)

Here is [an online tool](https://native2ascii.net/) which can help you to do the review work.

### Desired reviewers

@jenkinsci/chinese-localization-sig

### ScreenShot

保留了 `Timestamp` 未进行翻译

#### Job Build Console Log
image

#### Snippet Generator
image

#### Global Configuration
image

### CODE REVIEW

**Comment by yuezhuangshi** [comment]
@jenkinsci/chinese-localization-sig

**Comment by LinuxSuRen** [comment]
hi @yuezhuangshi thanks for your contribution. I'm kind of busy recently. But I'm still going to review your PRs as soon as I can.

**Comment by yuezhuangshi** [comment]
@LinuxSuRen Hi, Do you have time to take a look recently?

**Review by LinuxSuRen — APPROVED** [review]
Thanks for your effort. This looks good to me.

**Pull request merged**
