### PR TITLE
setup the cd for plugin

### PR DESCRIPTION
**Pull request by LinuxSuRen**
### Submitter checklist

- [ ] [Know translation specification](https://github.com/jenkins-zh/translation-spec/blob/master/specification.md)

Here is [an online tool](https://native2ascii.net/) which can help you to do the review work.

### Desired reviewers

@jenkinsci/chinese-localization-sig

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
Token is ready.

image

**Comment by NotMyFault** [comment]
> Token is ready.
> 
> image

For security reasons, the credentials are added by infrastructure tooling and rotated constantly.
User credentials shall never be used under any circumstance. I have removed them.

**Comment by LinuxSuRen** [comment]
Thanks for your tips.

**Comment by LinuxSuRen** [comment]
hi @NotMyFault I'm wondering if I can merge this PR once the upstream PR got merged.

**Comment by NotMyFault** [comment]
> hi @NotMyFault I'm wondering if I can merge this PR once the upstream PR got merged.

Once you see the tokens reappearing, for sure. But this time, they are added automatically, typically, within a few hours.

**Pull request merged**
